/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pun1shR (https://sketchfab.com/pun1shr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arrow-bd395aa897ad45a19505f63d82519df3
Title: arrow
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Arrow(props) {
  const { nodes, materials } = useGLTF("models/arrow.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0.099, -Math.PI / 2]} scale={0.061}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials["tex-global"]}
            position={[0, -1, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/arrow.glb");
